# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecd < Formula
  desc "Kubernetes GitOps deployment tool"
  homepage "https://github.com/kubecd/kubecd/"
  version "0.53.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kubecd/kubecd/releases/download/v0.53.0/kubecd_0.53.0_darwin_amd64.tar.gz"
    sha256 "378af156e2112e2e6dde9ad3cbc496773961d1b144489ba11bb9d07e0628fed2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kubecd/kubecd/releases/download/v0.53.0/kubecd_0.53.0_linux_amd64.tar.gz"
      sha256 "df8c32d808292af961d25e9b09eddddedd050683a8c2a6ec5335bcf98dfddc46"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubecd/kubecd/releases/download/v0.53.0/kubecd_0.53.0_linux_arm64.tar.gz"
        sha256 "b98a5d609e17c07860922bcd0f648fae7b2796e0ef55e6fa5647b065ae2d1b65"
      else
      end
    end
  end
  
  depends_on "kubernetes-cli"

  def install
    bin.install "kcd"
  end

  test do
    system "#{bin}/kcd version"
  end
end
