# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecd < Formula
  desc "Kubernetes GitOps deployment tool"
  homepage "https://github.com/zedge/kubecd/"
  version "0.51.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zedge/kubecd/releases/download/v0.51.0/kubecd_0.51.0_darwin_amd64.tar.gz"
    sha256 "07b4aa7e32e5ef9fca6166cd89ddbd0ad94981fa71f43488b4fc7f7de198f484"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/zedge/kubecd/releases/download/v0.51.0/kubecd_0.51.0_linux_amd64.tar.gz"
      sha256 "4d415df950e7e05ff5eac731e2672cc49fa9a4defe7d41eac39476bff64d6b39"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zedge/kubecd/releases/download/v0.51.0/kubecd_0.51.0_linux_arm64.tar.gz"
        sha256 "d627c7ad8d0a336e96db908adb23f8c622608860aba533ad2345552534d94379"
      else
      end
    end
  end
  
  depends_on "kubernetes-cli"
  depends_on "kubernetes-helm"

  def install
    bin.install "kcd"
  end

  test do
    system "#{bin}/kcd version"
  end
end
